### ISSUE TITLE
Support for ID class that supports values that arent UUIDs

### ISSUE THREAD

**Issue by mrhut10** [ocoda/event-sourcing#107]
I tried to use this libary last night, and really loved it, however found the `ID` only supporting uuids extremely limiting.

as in I have models that have identifiers provided by external venders, and are actually a publicKey identifier for a hardware device.

could it be supported injecting our own ID class that the library consumes or even a custom validator per instance of the `ID` used?

**Comment by drieshooghe** [comment]
Should now be possible through the following changes: https://github.com/ocoda/event-sourcing/pull/114
