### ISSUE TITLE
secondary indexes values on events/snapshots

### ISSUE THREAD

**Issue by mrhut10** [ocoda/event-sourcing#108]
currently we can query snapshots/events by a aggregate ID which is 100% unique to the modal instance.

what the suggested method if you need to query say all devices that owned by a particular client?
can we support 2nd indexes that arent unique, i.e. build up all snapshots and events for machines that have a particular clientId?

**Comment by drieshooghe** [comment]
The way it's set up right now doesn't allow much flexibility in terms of customizing indices. Eventually I want to make it possible to either provide a config or inject a custom event-/snapshot-store into the module like this:

```typescript
EventSourcingModule.forRootAsync({
      useFactory: (eventStore, snapshotStore) => ({
		events: [...Events],
		eventStore,
		snapshotStore,
	  }),
    }),
    inject: [CustomEventStore, CustomSnapshotStore]
```

That way, anyone can create a store-implementation that just extends the base-class but completely fits their needs.
Unfortunately I'm a bit short on time right now. If you're up for it, suggestions are more than welcome.
